// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVZT8Epo1fB0ma6Da5uDJb9tz0TgpaS4',
    appId: '1:69536054008:web:4ea77edf117854811e990d',
    messagingSenderId: '69536054008',
    projectId: 'poke-app-668a2',
    authDomain: 'poke-app-668a2.firebaseapp.com',
    storageBucket: 'poke-app-668a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZpAC-4GqWvFs_5i4da3PA1KOecZtMmY',
    appId: '1:69536054008:android:85668d56b3d0de731e990d',
    messagingSenderId: '69536054008',
    projectId: 'poke-app-668a2',
    storageBucket: 'poke-app-668a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOe_48lPFJjndD5ZTtdACJU_rQUlxVjjE',
    appId: '1:69536054008:ios:4cc4aeca9b8048b21e990d',
    messagingSenderId: '69536054008',
    projectId: 'poke-app-668a2',
    storageBucket: 'poke-app-668a2.appspot.com',
    iosClientId: '69536054008-e8dslc8pmfkd00ng2lnjasmv60b6599h.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokeAppDario',
  );
}
